# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ukweli.co
email:
description: Ukweli is a linux community based in Rwada



baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "http://ukweli.co" # the base hostname & protocol for your site

#sidebar
default-image:  # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by:
copyright:
   name:
   link: 'http://blog..com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: -demo

#social
facebook: http://facebook.com/
quora: http://quora.com/
twitter: http://twitter.com/@
github: http://github.com/

#facebook like box
fb-app-id:
fb-page-url: https://www.facebook.com//
fb-page-title:

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
